Fix re-redistribution
AMReX-Combustion/PeleC pull request #680
Opened 2023-08-17 20:55 UTC by marchdf

2023-08-22 17:40 UTC, baperry2 requested changes
Can you update the Docs to reflect the new re-re capability? https://amrex-combustion.github.io/PeleC/geometry/EB.html#re-redistribution

Also, I tried running the sod-4 case on Macbook and it fails with the following error:

> [Level 0 step 1] Advanced 32768 cells
[Level 1 step 1] ADVANCE at time 0 with dt = 0.0003961660569
... Computing MOL source term at t^{n} 
SIGILL Invalid, privileged, or ill-formed instruction
See Backtrace.0 file for details

> (base) bperry-38649s:Sod bperry$ cat Backtrace.0 
0: amrex::BLBackTrace::print_backtrace_info(__sFILE*) (in PeleC3d.gnu.ex) (AMReX_BLBackTrace.cpp:189)
1: amrex::BLBackTrace::handler(int) (in PeleC3d.gnu.ex) (AMReX_BLBackTrace.cpp:99)
2: _sigtramp (in libsystem_platform.dylib) + 56
4: amrex::EBFluxRegister::FineAdd(amrex::MFIter const&, std::__1::array<amrex::FArrayBox const*, 3ul> const&, double const*, double, amrex::FArrayBox const&, std::__1::array<amrex::FArrayBox const*, 3ul> const&, amrex::FArrayBox const&, amrex::RunOn) (in PeleC3d.gnu.ex) (AMReX_EBFluxRegister.cpp:149)
5: PeleC::update_flux_registers(double, amrex::MFIter const&, amrex::FabType const&, std::__1::array<amrex::FArrayBox const*, 3ul> const&, amrex::FArrayBox const&) (in PeleC3d.gnu.ex) (PeleC.cpp:0)
6: PeleC::getMOLSrcTerm(amrex::MultiFab const&, amrex::MultiFab&, double, double, double) (in PeleC3d.gnu.ex) (Diffusion.cpp:0)

2023-08-22 18:11 UTC, marchdf commented
Updated the docs, good catch. 

I will look into sod-4... I could swear I was using debug just fine...

2023-08-22 18:17 UTC, baperry2 commented
Hmm it seems to run fine for me in Debug but fails in regular mode. The most fun kind of issue to debug haha

2023-08-22 18:21 UTC, jrood-nrel commented
I'm worried that error is buffer overflowing into instruction pointer code and why it's saying bad instruction.

2023-08-22 18:21 UTC, jrood-nrel commented
What does ASAN say?

2023-08-22 20:14 UTC, marchdf commented
Documenting here for posterity:

What Bruce saw is a typical thing we see on OSX and clang every so often. We guard against this in cmake with `maytrap` https://github.com/AMReX-Combustion/PeleC/blob/development/CMake/SetAmrexCompileFlags.cmake#L8. This doesn't happen on llvm+linux. So it's hard to replicate... I commented out the trapping so we only do it when we actually want to (which should just be in debug mode).

2023-08-22 20:29 UTC, jrood-nrel approved these changes

2023-08-22 21:11 UTC, marchdf commented
We are going to wait on https://github.com/AMReX-Codes/amrex/pull/3506 before we merge this

2023-08-22 21:25 UTC, baperry2 approved these changes
Thanks for updating the documentation. 

I can successfully run the test case with fpe trapping turned off and the results look reasonable.

2023-08-23 16:47 UTC, marchdf commented
# Pics of what we can do now:
## EB-C8:
![Screen Shot 2023-08-23 at 10 42 30](https://github.com/AMReX-Combustion/PeleC/assets/15038415/07bca93d-0829-4e1f-822a-9dc540ed3b5b)

## Sod + sphere:
![Screen Shot 2023-08-23 at 10 45 53](https://github.com/AMReX-Combustion/PeleC/assets/15038415/235cca1f-b880-41f1-99f2-eae34b021f78)
![Screen Shot 2023-08-23 at 10 46 32](https://github.com/AMReX-Combustion/PeleC/assets/15038415/0e129465-0151-4c93-9042-c399837067b6)

2023-08-23 21:59 UTC, drummerdoc commented
Excellent!  Getting better all the time!

2023-08-23 22:02 UTC, merged